# Generated by Django 4.0.6 on 2022-07-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
